name: Build Capacitor Android App

on:
  workflow_run:
    workflows: ["Lint & Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.18
        cache: "npm"
    - run: npm install
    - run: npx nx export tasks-client
      env:
        NEXT_PUBLIC_BASE_API_URL: ${{ vars.NEXT_PUBLIC_BASE_API_URL }}
    - run: npx nx cap:sync tasks-client
    - run: npx nx cap:update tasks-client
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - run: frontend/tasks-client/android/gradlew -p frontend/tasks-client/android assembleDebug
    - uses: actions/upload-artifact@v3
      with:
        name: Debug APK
        path: frontend/tasks-client/android/app/build/outputs/apk/debug/app-debug.apk
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: tasks-58023
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIALS }}
        groups: testers
        file: frontend/tasks-client/android/app/build/outputs/apk/debug/app-debug.apk
